import { DayMenu, InventoryItem, Project, Reminder, ShoppingItem, Task, TimeBlock } from '../types';

export const INITIAL_TASKS: Task[] = [
  {
    id: 't-1',
    title: 'Revisión y envío de informe de métricas Q3',
    priority: 'Alta',
    dueDate: '2026-09-21',
    dueTime: '11:30',
    category: 'Trabajo',
    completed: false,
    notes: 'Incluir gráficos comparativos de rendimiento.',
  },
  {
    id: 't-2',
    title: 'Coordinar mantenimiento de caldera / calefacción',
    priority: 'Alta',
    dueDate: '2026-09-21',
    dueTime: '15:00',
    category: 'Hogar',
    completed: false,
    notes: 'Llamar al técnico para confirmar visita de las 16:30.',
  },
  {
    id: 't-3',
    title: 'Preparación de propuesta para cliente estratégico',
    priority: 'Alta',
    dueDate: '2026-09-22',
    dueTime: '18:00',
    category: 'Trabajo',
    completed: false,
    notes: 'Bloque de foco profundo de 2 horas reservado.',
  },
  {
    id: 't-4',
    title: 'Conciliación bancaria mensual y pago de servicios',
    priority: 'Media',
    dueDate: '2026-09-23',
    dueTime: '10:00',
    category: 'Finanzas',
    completed: false,
    notes: 'Verificar débito automático de electricidad y agua.',
  },
  {
    id: 't-5',
    title: 'Compra semanal en supermercado y verdulería',
    priority: 'Media',
    dueDate: '2026-09-21',
    dueTime: '19:00',
    category: 'Hogar',
    completed: false,
    notes: 'Llevar lista consolidada generada por rubro.',
  },
];

export const INITIAL_REMINDERS: Reminder[] = [
  {
    id: 'r-1',
    title: 'Firma y envío urgente de contrato de renovación de póliza',
    executionDate: '2026-09-21',
    executionTime: '09:00',
    priority: 'Alta',
    isAlertActive: true,
    status: 'Pendiente',
    contextTag: 'Compromiso Clave',
    notes: 'Requiere firma digital y copia a la correduría.',
  },
  {
    id: 'r-2',
    title: 'Tomar medicación matutina y chequeo de presión arterial',
    executionDate: '2026-09-21',
    executionTime: '08:15',
    priority: 'Alta',
    isAlertActive: true,
    status: 'Pendiente',
    contextTag: 'Salud',
    notes: 'Registrar valor en la libreta clínica.',
  },
  {
    id: 'r-alert-urgent',
    title: 'Vencimiento de pago de servicios públicos y nómina de servicios',
    executionDate: '2026-09-21',
    executionTime: '11:00',
    priority: 'Alta',
    isAlertActive: true,
    status: 'Pendiente',
    contextTag: 'Finanzas',
    notes: 'Evitar cargos por mora en la cuenta corporativa.',
  },
  {
    id: 'r-3',
    title: 'Llamada de seguimiento con Proveedor de Logística',
    executionDate: '2026-09-21',
    executionTime: '14:30',
    priority: 'Media',
    isAlertActive: true,
    status: 'Pendiente',
    contextTag: 'Seguimiento',
    notes: 'Confirmar entrega del lote de suministros de oficina.',
  },
  {
    id: 'r-4',
    title: 'Descongelar pechugas de pollo para cena planificada de mañana',
    executionDate: '2026-09-21',
    executionTime: '20:00',
    priority: 'Media',
    isAlertActive: false,
    status: 'Pendiente',
    contextTag: 'Hogar & Alimentación',
    notes: 'Bajar del congelador a la heladera para descongelado seguro.',
  },
  {
    id: 'r-5',
    title: 'Cierre de ciclo contable mensual y envío al asesor fiscal',
    executionDate: '2026-09-24',
    executionTime: '12:00',
    priority: 'Alta',
    isAlertActive: true,
    status: 'Pendiente',
    contextTag: 'Finanzas',
    notes: 'Adjuntar extractos bancarios conciliados.',
  },
  {
    id: 'r-6',
    title: 'Revisión periódica de suscripciones de software y licencias',
    executionDate: '2026-09-25',
    executionTime: '17:00',
    priority: 'Baja',
    isAlertActive: false,
    status: 'Pendiente',
    contextTag: 'Administración',
    notes: 'Evaluar bajas de servicios no utilizados.',
  },
  {
    id: 'r-7',
    title: 'Regar jardín vertical y comprobar programador de riego',
    executionDate: '2026-09-21',
    executionTime: '19:30',
    priority: 'Baja',
    isAlertActive: false,
    status: 'Pendiente',
    contextTag: 'Hogar',
  }
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  // Limpieza
  {
    id: 'inv-1',
    name: 'Detergente para vajilla concentrado',
    category: 'Limpieza',
    stockStatus: 'Por agotar',
    urgency: 'Urgente',
    quantity: 1,
    minQuantity: 2,
    unit: 'botella 750ml',
    suggestedStoreCategory: 'Limpieza',
    lastChecked: '2026-09-20',
  },
  {
    id: 'inv-2',
    name: 'Lavandina / Cloro desinfectante',
    category: 'Limpieza',
    stockStatus: 'Agotado',
    urgency: 'Urgente',
    quantity: 0,
    minQuantity: 2,
    unit: 'litros',
    suggestedStoreCategory: 'Limpieza',
    lastChecked: '2026-09-20',
  },
  {
    id: 'inv-3',
    name: 'Jabón líquido para lavarropas',
    category: 'Limpieza',
    stockStatus: 'Suficiente',
    urgency: 'Reposición rutinaria',
    quantity: 3,
    minQuantity: 1,
    unit: 'litros',
    suggestedStoreCategory: 'Limpieza',
    lastChecked: '2026-09-18',
  },
  {
    id: 'inv-4',
    name: 'Bolsas de residuos reforzadas (50x65)',
    category: 'Limpieza',
    stockStatus: 'Por agotar',
    urgency: 'Normal',
    quantity: 4,
    minQuantity: 10,
    unit: 'unidades',
    suggestedStoreCategory: 'Limpieza',
    lastChecked: '2026-09-19',
  },

  // Higiene
  {
    id: 'inv-5',
    name: 'Papel higiénico hoja doble',
    category: 'Higiene',
    stockStatus: 'Por agotar',
    urgency: 'Urgente',
    quantity: 2,
    minQuantity: 8,
    unit: 'rollos',
    suggestedStoreCategory: 'Limpieza',
    lastChecked: '2026-09-20',
  },
  {
    id: 'inv-6',
    name: 'Pasta dental con flúor',
    category: 'Higiene',
    stockStatus: 'Suficiente',
    urgency: 'Reposición rutinaria',
    quantity: 2,
    minQuantity: 1,
    unit: 'tubos',
    suggestedStoreCategory: 'Limpieza',
    lastChecked: '2026-09-15',
  },
  {
    id: 'inv-7',
    name: 'Jabón corporal neutro',
    category: 'Higiene',
    stockStatus: 'Suficiente',
    urgency: 'Reposición rutinaria',
    quantity: 4,
    minQuantity: 2,
    unit: 'pastillas',
    suggestedStoreCategory: 'Limpieza',
    lastChecked: '2026-09-15',
  },

  // Despensa
  {
    id: 'inv-8',
    name: 'Aceite de oliva virgen extra',
    category: 'Despensa',
    stockStatus: 'Por agotar',
    urgency: 'Normal',
    quantity: 200,
    minQuantity: 1000,
    unit: 'ml',
    suggestedStoreCategory: 'Almacén',
    lastChecked: '2026-09-20',
  },
  {
    id: 'inv-9',
    name: 'Café tostado en grano / molido',
    category: 'Despensa',
    stockStatus: 'Suficiente',
    urgency: 'Reposición rutinaria',
    quantity: 500,
    minQuantity: 250,
    unit: 'g',
    suggestedStoreCategory: 'Almacén',
    lastChecked: '2026-09-19',
  },
  {
    id: 'inv-10',
    name: 'Arroz integral / Carnaroli',
    category: 'Despensa',
    stockStatus: 'Agotado',
    urgency: 'Urgente',
    quantity: 0,
    minQuantity: 1,
    unit: 'kg',
    suggestedStoreCategory: 'Almacén',
    lastChecked: '2026-09-20',
  },
  {
    id: 'inv-11',
    name: 'Avena tradicional en copos',
    category: 'Despensa',
    stockStatus: 'Suficiente',
    urgency: 'Reposición rutinaria',
    quantity: 800,
    minQuantity: 400,
    unit: 'g',
    suggestedStoreCategory: 'Almacén',
    lastChecked: '2026-09-17',
  },

  // Insumos Generales
  {
    id: 'inv-12',
    name: 'Pilas alcalinas AA',
    category: 'Insumos Generales',
    stockStatus: 'Suficiente',
    urgency: 'Reposición rutinaria',
    quantity: 6,
    minQuantity: 2,
    unit: 'unidades',
    suggestedStoreCategory: 'Almacén',
    lastChecked: '2026-09-10',
  },
  {
    id: 'inv-13',
    name: 'Filtros de agua para jarra',
    category: 'Insumos Generales',
    stockStatus: 'Agotado',
    urgency: 'Normal',
    quantity: 0,
    minQuantity: 1,
    unit: 'cartuchos',
    suggestedStoreCategory: 'Almacén',
    lastChecked: '2026-09-20',
  },
];

export const INITIAL_WEEKLY_MENU: DayMenu[] = [
  {
    day: 'Lunes',
    desayuno: {
      name: 'Tostadas integrales con palta y huevo poché + café',
      ingredients: ['Pan integral', 'Paltas / Aguacates', 'Huevos', 'Café'],
    },
    almuerzo: {
      name: 'Bowl de quinoa con pechuga grillada, espinaca y tomates cherry',
      ingredients: ['Quinoa', 'Pechuga de pollo', 'Espinaca fresca', 'Tomates cherry', 'Aceite de oliva'],
    },
    merienda: {
      name: 'Yogur natural con nueces, semillas y fruta de estación',
      ingredients: ['Yogur natural', 'Nueces', 'Manzanas'],
    },
    cena: {
      name: 'Filete de merluza con papas al vapor y brócoli salteado',
      ingredients: ['Filet de merluza', 'Papas', 'Brócoli', 'Limón'],
    },
  },
  {
    day: 'Martes',
    desayuno: {
      name: 'Porridge de avena caliente con canela, plátano y chía',
      ingredients: ['Avena', 'Leche desnatada', 'Plátano', 'Canela'],
    },
    almuerzo: {
      name: 'Wok de ternera magra con morrones, zanahorias y arroz',
      ingredients: ['Carne vacuna magra', 'Arroz integral', 'Morrones rojos', 'Zanahorias', 'Salsa de soja'],
    },
    merienda: {
      name: 'Tostada de masa madre con queso magro y té verde',
      ingredients: ['Pan integral', 'Queso magro', 'Té verde'],
    },
    cena: {
      name: 'Tortilla de espinacas y cebolla con ensalada de rúcula y parmesano',
      ingredients: ['Huevos', 'Espinaca fresca', 'Cebollas', 'Rúcula', 'Queso parmesano'],
    },
  },
  {
    day: 'Miércoles',
    desayuno: {
      name: 'Omelette de claras con champiñones y tostada',
      ingredients: ['Huevos', 'Champiñones', 'Pan integral', 'Café'],
    },
    almuerzo: {
      name: 'Guiso ligero de lentejas con calabaza y dados de pechuga',
      ingredients: ['Lentejas secas', 'Calabaza / Zapallo', 'Pechuga de pollo', 'Cebollas', 'Zanahorias'],
    },
    merienda: {
      name: 'Batido proteico de frutos rojos con leche de almendras',
      ingredients: ['Frutos rojos congelados', 'Leche de almendras'],
    },
    cena: {
      name: 'Salmón o trucha al horno con espárragos y puré de coliflor',
      ingredients: ['Salmón fresco', 'Espárragos', 'Coliflor', 'Aceite de oliva'],
    },
  },
  {
    day: 'Jueves',
    desayuno: {
      name: 'Pancakes de avena y banana con hilos de miel',
      ingredients: ['Avena', 'Plátano', 'Huevos', 'Miel'],
    },
    almuerzo: {
      name: 'Pasta integral con salsa casera de tomates, albahaca y carne magra',
      ingredients: ['Pasta integral', 'Tomates perita', 'Albahaca fresca', 'Carne picada especial'],
    },
    merienda: {
      name: 'Puñado de almendras y pera en rodajas con infusión',
      ingredients: ['Almendras', 'Peras'],
    },
    cena: {
      name: 'Crema tibia de zapallo y zanahoria con semillas de girasol tostadas',
      ingredients: ['Calabaza / Zapallo', 'Zanahorias', 'Cebollas', 'Queso crema'],
    },
  },
  {
    day: 'Viernes',
    desayuno: {
      name: 'Tostadas con queso untable, semillas y rodajas de tomate',
      ingredients: ['Pan integral', 'Queso untable', 'Tomates redondos', 'Café'],
    },
    almuerzo: {
      name: 'Tarta integral de calabaza, puerros y queso con hojas verdes',
      ingredients: ['Masa para tarta integral', 'Puerros', 'Calabaza / Zapallo', 'Huevos', 'Queso magro'],
    },
    merienda: {
      name: 'Tazón de yogur griego con granola casera y arándanos',
      ingredients: ['Yogur griego', 'Arándanos frescos', 'Granola'],
    },
    cena: {
      name: 'Fajitas caseras de pollo salteado con pimientos y guacamole',
      ingredients: ['Pechuga de pollo', 'Pimientos verdes y rojos', 'Paltas / Aguacates', 'Tortillas integrales'],
    },
  },
  {
    day: 'Sábado',
    desayuno: {
      name: 'Huevos revueltos sobre pan brioche artesanal y jugo de naranja exprimido',
      ingredients: ['Huevos', 'Naranjas para jugo', 'Pan brioche', 'Manteca'],
    },
    almuerzo: {
      name: 'Asado o solomillo magro a la plancha con ensalada mixta y papas rústicas',
      ingredients: ['Corte de carne vacuna / solomillo', 'Papas', 'Lechuga mantecosa', 'Tomates redondos'],
    },
    merienda: {
      name: 'Café latte frío con galletas de avena y pasas caseras',
      ingredients: ['Café', 'Leche desnatada', 'Galletas de avena'],
    },
    cena: {
      name: 'Pizza casera masa fina con rúcula, jamón crudo y tomates secos',
      ingredients: ['Harina integral / 000', 'Levadura', 'Muzzarella', 'Rúcula', 'Jamón crudo'],
    },
  },
  {
    day: 'Domingo',
    desayuno: {
      name: 'Brunch familiar: Tostadas francesas ligeras con frutas frescas',
      ingredients: ['Pan de molde', 'Huevos', 'Frutillas / Fresas', 'Canela'],
    },
    almuerzo: {
      name: 'Paella o arroz con mariscos y verduras salteadas',
      ingredients: ['Arroz bomba', 'Mix de mariscos / langostinos', 'Pimientos rojos', 'Azafrán'],
    },
    merienda: {
      name: 'Té con tostadas de pan de semillas y mermelada reducida en azúcar',
      ingredients: ['Pan integral de semillas', 'Mermelada'],
    },
    cena: {
      name: 'Sopa reconstituyente de verduras con fideos de arroz y huevo poché',
      ingredients: ['Caldo de verduras casero', 'Fideos de arroz', 'Zanahorias', 'Huevos', 'Ciboulette'],
    },
  },
];

export const INITIAL_TIME_BLOCKS: TimeBlock[] = [
  {
    id: 'tb-1',
    timeRange: '06:30 - 08:00',
    blockName: 'Rutina Matutina y Bienestar',
    type: 'Rutina',
    priority: 'Alta',
    tasks: ['Hidratación y 20 min de movilidad', 'Ducha fría y preparación personal', 'Desayuno nutritivo'],
    completed: true,
  },
  {
    id: 'tb-2',
    timeRange: '08:00 - 11:30',
    blockName: 'Bloque de Foco Profundo (Deep Work)',
    type: 'Foco Profundo',
    priority: 'Alta',
    tasks: ['Informe de métricas estratégicas Q3', 'Revisión y diseño de entregables clave', 'Cero notificaciones'],
    completed: false,
  },
  {
    id: 'tb-3',
    timeRange: '11:30 - 13:00',
    blockName: 'Reuniones y Comunicación Ejecutiva',
    type: 'Reuniones',
    priority: 'Media',
    tasks: ['Sincronización semanal con equipo', 'Revisión y firma de contratos', 'Llamadas a clientes'],
    completed: false,
  },
  {
    id: 'tb-4',
    timeRange: '13:00 - 14:15',
    blockName: 'Alimentación y Pausa Activa',
    type: 'Hogar & Alimentación',
    priority: 'Media',
    tasks: ['Almuerzo planificado (Bowl de quinoa y pollo)', 'Paseo al aire libre de 15 minutos'],
    completed: false,
  },
  {
    id: 'tb-5',
    timeRange: '14:15 - 16:45',
    blockName: 'Ejecución Operativa & Proyectos',
    type: 'Operativo',
    priority: 'Alta',
    tasks: ['Atención a compromisos y seguimiento', 'Desglose de próximos hitos del proyecto Q4'],
    completed: false,
  },
  {
    id: 'tb-6',
    timeRange: '16:45 - 18:00',
    blockName: 'Logística del Hogar y Cierre de Día',
    type: 'Hogar & Alimentación',
    priority: 'Media',
    tasks: ['Revisión de stock crítico del hogar', 'Verificación de alertas y compras pendientes', 'Planificación de agenda de mañana'],
    completed: false,
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Optimización y Reestructuración de Finanzas & Despensa del Hogar',
    goal: 'Estandarizar el sistema de reposición periódica de insumos, eliminar compras duplicadas y reducir tiempos en supermercado en un 40%.',
    deadline: '2026-10-05',
    progress: 60,
    steps: [
      {
        id: 'ps-1',
        title: 'Auditoría física completa de despensa, higiene y limpieza',
        timeEstimate: '1 hora',
        priority: 'Alta',
        suggestedTiming: 'Sábado mañana',
        completed: true,
      },
      {
        id: 'ps-2',
        title: 'Definir puntos de pedido y stock mínimo para insumos críticos',
        timeEstimate: '45 min',
        priority: 'Alta',
        suggestedTiming: 'Lunes bloque operativo',
        completed: true,
      },
      {
        id: 'ps-3',
        title: 'Establecer lista de compras por rubros fija para verdulería y carnicería',
        timeEstimate: '30 min',
        priority: 'Media',
        suggestedTiming: 'Martes bloque hogar',
        completed: false,
      },
      {
        id: 'ps-4',
        title: 'Configuración de reposición automática mensual para productos no perecederos',
        timeEstimate: '40 min',
        priority: 'Media',
        suggestedTiming: 'Jueves cierre',
        completed: false,
      },
    ],
  },
  {
    id: 'proj-2',
    name: 'Presentación Estratégica Ejecutiva Q4',
    goal: 'Presentar roadmap de expansión, presupuesto de operaciones y asignación de recursos ante la junta directiva.',
    deadline: '2026-09-28',
    progress: 40,
    steps: [
      {
        id: 'ps-21',
        title: 'Consolidar métricas de rendimiento y desvíos presupuestarios Q3',
        timeEstimate: '2 horas',
        priority: 'Alta',
        suggestedTiming: 'Lunes foco profundo',
        completed: true,
      },
      {
        id: 'ps-22',
        title: 'Redactar narrativa de crecimiento y objetivos estratégicos',
        timeEstimate: '1.5 horas',
        priority: 'Alta',
        suggestedTiming: 'Martes foco profundo',
        completed: false,
      },
      {
        id: 'ps-23',
        title: 'Diseño de diapositivas ejecutivas con tablas sintéticas',
        timeEstimate: '2 horas',
        priority: 'Media',
        suggestedTiming: 'Miércoles foco profundo',
        completed: false,
      },
      {
        id: 'ps-24',
        title: 'Simulación y ensayo de preguntas críticas',
        timeEstimate: '1 hora',
        priority: 'Alta',
        suggestedTiming: 'Jueves operativo',
        completed: false,
      },
    ],
  },
];
